Criar tabelas temporarias com a criação de dados e schemas

In [0]:
import pyspark.sql.functions as F

dados1 = [
    (1, "Anderson", 10000),
    (2, "Kenedy", 20000),
    (3, "Billy", 23000),
    (4, "Andy", 23000),
    (5, "Mary", 24000),
    (6, "Eduardo", 19000),
    (7, "Mendes", 15000),
    (8, "Keyth", 18000),
    (9, "Truman", 21000),
]

schema1 = ["id", "nome", "salario"]

spark.createDataFrame(data=dados1,schema=schema1).createOrReplaceTempView('funcionarios')

dados2 = [
    (1, "Delhi", "India"),
    (2, "Tamil nadu", "India"),
    (3, "London", "UK"),
    (4, "Sydney", "Australia"),
    (8, "New York", "USA"),
    (9, "California", "USA"),
    (10, "New Jersey", "USA"),
    (11, "Texas", "USA"),
    (12, "Chicago", "USA"),
]

schema2 = ["id", "local", "pais"]

spark.createDataFrame(data=dados2,schema=schema2).createOrReplaceTempView('localizacoes')

In [0]:
%sql
SELECT *
FROM funcionarios

id,nome,salario
1,Anderson,10000
2,Kenedy,20000
3,Billy,23000
4,Andy,23000
5,Mary,24000
6,Eduardo,19000
7,Mendes,15000
8,Keyth,18000
9,Truman,21000

In [0]:
%sql
SELECT *
FROM localizacoes

id,local,pais
1,Delhi,India
2,Tamil nadu,India
3,London,UK
4,Sydney,Australia
8,New York,USA
9,California,USA
10,New Jersey,USA
11,Texas,USA
12,Chicago,USA

SELECT campos 

FROM tabela1

INNER JOIN tabela2 

ON tabela1.coluna = tabela2.coluna

INNER JOIN - pega os dados da interseção entre ambos

In [0]:
%sql
SELECT *
FROM funcionarios INNER JOIN localizacoes
ON funcionarios.id = localizacoes.id

id,nome,salario,id,local,pais
1,Anderson,10000,1,Delhi,India
2,Kenedy,20000,2,Tamil nadu,India
3,Billy,23000,3,London,UK
4,Andy,23000,4,Sydney,Australia
8,Keyth,18000,8,New York,USA
9,Truman,21000,9,California,USA

Mesma estrutura do Inner Join

Pega todos os dados da tabela da esquerda e mostra os que da match com o da direita

Nos campos que não há correpodencia, ele acrescenta null

Não mostra os campos da direita que não deram match

In [0]:
%sql
SELECT *
FROM funcionarios LEFT OUTER JOIN localizacoes
ON funcionarios.id = localizacoes.id

id,nome,salario,id,local,pais
1,Anderson,10000,1,Delhi,India
2,Kenedy,20000,2,Tamil nadu,India
3,Billy,23000,3,London,UK
4,Andy,23000,4,Sydney,Australia
5,Mary,24000,null,null,null
6,Eduardo,19000,null,null,null
7,Mendes,15000,null,null,null
8,Keyth,18000,8,New York,USA
9,Truman,21000,9,California,USA

Mesma estrutura do Inner Join

Pega todos os dados da tabela da direita e mostra os que da match com o da esquerda

Nos campos que não há correpodencia, ele acrescenta null

Não mostra os campos da esquerda que não deram match

In [0]:
%sql
SELECT *
FROM funcionarios RIGHT OUTER JOIN localizacoes
ON funcionarios.id = localizacoes.id

id,nome,salario,id,local,pais
1,Anderson,10000,1,Delhi,India
2,Kenedy,20000,2,Tamil nadu,India
3,Billy,23000,3,London,UK
4,Andy,23000,4,Sydney,Australia
8,Keyth,18000,8,New York,USA
9,Truman,21000,9,California,USA
null,null,null,10,New Jersey,USA
null,null,null,11,Texas,USA
null,null,null,12,Chicago,USA